# Generated by Django 3.2.4 on 2021-07-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_me',
            name='socrce',
            field=models.IntegerField(default=0),
        ),
    ]
