# Generated by Django 3.2.4 on 2021-07-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_test', '0003_local_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_me',
            name='Stock_remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
