# Generated by Django 3.2.4 on 2021-07-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_test', '0004_alter_stock_me_stock_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_me',
            name='socrce',
            field=models.CharField(max_length=200),
        ),
    ]
