# Generated by Django 3.2.4 on 2021-07-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_test', '0006_alter_stock_me_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_me',
            name='Stock_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock_me',
            name='socrce',
            field=models.IntegerField(default=0),
        ),
    ]
