# Generated by Django 3.2.4 on 2021-07-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_test', '0007_auto_20210714_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_me',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='stock_img'),
        ),
    ]
