# Generated by Django 3.2.5 on 2021-07-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_test', '0009_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(blank=True, default='default.png', null=True, upload_to='img_product')),
                ('Stock_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web_test.stock_me')),
            ],
        ),
    ]
